# Data source configurations
# Configure different data providers with their specific parameters

tushare:
  type: "tushare"
  enabled: true
  priority: 1
  timeout: 30
  retry_count: 3
  retry_delay: 1.0
  rate_limit: 200  # requests per hour for basic plan
  api_token: "${TUSHARE_TOKEN}"  # Will be loaded from environment
  extra_params:
    risk_free_rate: 0.03
    max_days_back: 5

wind:
  type: "wind"
  enabled: false  # Disabled by default as it requires Wind Terminal
  priority: 2
  timeout: 45
  retry_count: 2
  retry_delay: 2.0
  base_url: "https://wind.com.cn/api"
  extra_params:
    use_terminal: true
    terminal_timeout: 60

eastmoney:
  type: "eastmoney"
  enabled: false  # Placeholder for future implementation
  priority: 3
  timeout: 20
  retry_count: 3
  retry_delay: 1.0
  base_url: "https://api.eastmoney.com"
  extra_params:
    free_tier: true

# mock data source configuration removed for production security
# All data must come from real market APIs
    option_count: 100